#!/bin/bash
#
# AWS Elastic Beanstalk Nginx/PHP-FPM Configuration
#
# @author    James Leckenby <me@jleck.co.uk>
# @link      http://jleck.co.uk
# @copyright 2013 James Leckenby
# @license   MIT License
# @version   1.0
#

# Install Composer
echo 'Installing Composer'
/usr/bin/curl -s http://getcomposer.org/installer | /usr/bin/php
if [ ! -f 'composer.phar' ]; then
    echo 'Error downloading Composer'
    exit 1
fi

# End script
/bin/mv composer.phar /usr/bin/composer
/bin/chown -R elasticbeanstalk:elasticbeanstalk /usr/bin/composer
exit 0