#!/bin/bash
#
# AWS Elastic Beanstalk Nginx/PHP-FPM Configuration
#
# @author    James Leckenby <me@jleck.co.uk>
# @link      http://jleck.co.uk
# @copyright 2013 James Leckenby
# @license   MIT License
# @version   1.0
#

# Install rsyslog-gnutls to support rsyslog forwarding using TLS
echo 'Setting up rsyslog fowarding for logentries'
/usr/bin/yum -q -y install rsyslog-gnutls

# Alter Hostmanager and merge
/bin/sed -i "46i\ " /opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/applications/phpapplication.rb
/bin/sed -i "47i\          HostManager.log 'Updating Logentries options'" /opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/applications/phpapplication.rb
/bin/sed -i "48i\          ElasticBeanstalk::HostManager::Utils::LogentriesUtil.update_logentries_conf(ElasticBeanstalk::HostManager.config.application['Environment Properties'])" /opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/applications/phpapplication.rb
/bin/cp -rf /tmp/build/addons/logentries/etc /
/bin/cp -rf /tmp/build/addons/logentries/opt /

# End script
/bin/chown -R elasticbeanstalk:elasticbeanstalk /etc/rsyslog.d
/sbin/chkconfig varnish off
exit 0