#!/bin/bash
#
# AWS Elastic Beanstalk Nginx/PHP-FPM Configuration
#
# @author    James Leckenby <me@jleck.co.uk>
# @link      http://jleck.co.uk
# @copyright 2013 James Leckenby
# @license   MIT License
# @version   1.0
#

# Install Memcache
echo 'Installing Memcache'
/usr/bin/yum -q -y install memcached
if [ $? -ne 0 ]; then
    echo 'Error trying to install Memcache'
    exit 1
fi

# End script
exit 0