#!/bin/bash
#
# AWS Elastic Beanstalk Nginx/PHP-FPM Configuration
#
# @author    James Leckenby <me@jleck.co.uk>
# @link      http://jleck.co.uk
# @copyright 2013 James Leckenby
# @license   MIT License
# @version   1.0
#

# Install Nginx
echo 'Installing Varnish'
/usr/bin/yum -q -y install varnish
if [ $? -ne 0 ]; then
    echo 'Error trying to install Varnish'
    exit 1
fi

# Alter Nginx config and merge
/bin/sed -i "110i\    listen 8080;" /opt/elasticbeanstalk/srv/hostmanager/lib/elasticbeanstalk/hostmanager/utils/nginxutil.rb
/bin/cp -rf /tmp/build/addons/varnish/etc /
/bin/cp -rf /tmp/build/addons/varnish/opt /

# Clear autostart and end script
/sbin/chkconfig varnish off
exit 0